#!/bin/sh
echo "Starting Product Analytics Build"

SRC="${BUILD_DIR%Build/*}/SourcePackages/checkouts/ProductAnalytics"

cd $SRC

/usr/bin/xcrun --sdk macosx swift build -v \
    -Xswiftc "-sdk" \
    -Xswiftc "`xcrun --sdk macosx --show-sdk-path`"

/usr/bin/xcrun --sdk macosx swift run ProductAnalytics --output-folder "my test"
