name: Swift Lint

on:
  push:
    paths:
      - '.github/workflows/ios_swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
    branches:
      - '**'

jobs:
  SwiftLint:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        
#       - name: Install Swift lint
#         run: |
#             brew install swiftlint

      - name: Lint
        run: |
            FILES=$(git diff main --name-only | grep ".*\.swift$")
            if (( ${#FILES[@]} )); then
                swiftlint --config .swiftlint.yml $FILES
            fi