name: Unit Tests

on:
  push:
    branches:
      - '**'
  
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
    
jobs:
  test:
    name: Unit Tests
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Unit Tests
        run: |
            swift test --enable-code-coverage
            
      - name: Install Xcode Command line tools
        run: |
            # who are you?
            whoami
            #check if Xcode package is installed
            #if installed it will display : /Applications/Xcode.app/Contents/Developer
            xcode-select -p
            # install Xcode command line tools if not installed
            INSTALLED=$(xcode-select -p 1>/dev/null;echo $?)
            if [[ $INSTALLED -ne 0 ]]; then
                xcode-select --install
                #verify successfull installation
                xcode-select -p
                #verify if GCC is installed
                gcc --version
            fi
        
      - name: Generate Coverage Report
        run: |
            ARCH=$(uname -m)
            /Library/Developer/CommandLineTools/usr/bin/llvm-cov \
              report ".build/${ARCH}-apple-macosx/debug/ProductAnalysisPackageTests.xctest/Contents/MacOS/ProductAnalysisPackageTests" \
              -instr-profile=".build/${ARCH}-apple-macosx/debug/codecov/default.profdata" \
              -use-color
      